<section>
    <div class="row">
        <div class="col-lg-3">
            <h2 class="title-font font-medium text-3xl text-gray-900">2.7K</h2>
            <p class="leading-relaxed">Users</p>
        </div>
        <div class="col-lg-3">
            <h2 class="title-font font-medium text-3xl text-gray-900">35</h2>
            <p class="leading-relaxed">Downloads</p>
        </div>
        <div class="col-lg-3">
            <h2 class="title-font font-medium text-3xl text-gray-900">1.8K</h2>
            <p class="leading-relaxed">Subscribes</p>
        </div>
        <div class="col-lg-3">
            <h2 class="title-font font-medium text-3xl text-gray-900">4</h2>
            <p class="leading-relaxed">Products</p>
        </div>

    </div>
</section>